function [TEM,surM] = TE(xV,yV,h,m,tau,k,nsur)
% function [TEM,surM] = TE(xV,yV,h,m,tau,k,nsur)
% This function estimates the bivariate Transfer Entropy (TE) from the observed 
% time series X and Y, for the directions X-> Y and Y-> X
% Also, TE is estimated from nsur surrogate time series which are generated by 
% time shuffling the reconstructed vectors of the driving time series 
% The k-nearest neighbor (KNN) estimator is used (Kraskov et al., 2004)
%INPUTS
% - xV,yV         : time series, each of size: n x 1
% - k             : number of neighbors for KNN estimator
% - h             : h steps ahead of xV
% - m             : embendding dimension 
% - tau           : lag 
% - nsur          : number of surrogates
% OUTPUTS
% - TEM           : TEM = [TE(X->Y)  TE(Y->X)] (size: 1 x 2)
% - surM          : surM = [TE(X*->Y) TE(Y*->X)] (size: nsur x 2)
%                   X*, Y*: time-shifted time series of X and Y, respectively 
%
% Code written by Angeliki Papana (University of Macedonia, Greece)  


% rescale time series to be in [0,1] 
xV = rangescale(xV); 
yV = rangescale(yV);

N = length(xV);
M = (m-1)*tau;

xVh = NaN*ones(N-h-M,1);
yVh = NaN*ones(N-h-M,1);
xM = NaN*ones(N-h-M,m);
yM = NaN*ones(N-h-M,m);

for i = M+1:N-h 
    xVh(i-M,1) = xV(i+h);
    yVh(i-M,1) = yV(i+h);
    xM(i-M,:) = xV(i-(m-1)*tau:tau:i);
    yM(i-M,:) = yV(i-(m-1)*tau:tau:i);
end

TEx = cmikra1n(yVh,xM,yM,k);          % TE(X->Y)
TEy = cmikra1n(xVh,yM,xM,k);          % TE(Y->X)

TEM = [TEx TEy];   


% Surrogate PTE values - time shifted surrogates
offsetfrac = 0.1; % For time-shifted surrogates
offset = round(N*offsetfrac/2); % time offset for surrogates

sTEx  = NaN*ones(nsur,1);
sTEy  = NaN*ones(nsur,1);

for isur = 1:nsur
    istart = offset+unidrnd(N-2*offset);
    sxV = xV([istart:N 1:istart-1],:);
    syV = yV([istart:N 1:istart-1],:); 
    sxM = NaN*ones(N-h-M,m);
    syM = NaN*ones(N-h-M,m);   
    for i = M+1:N-h 
        sxM(i-M,:) = sxV(i-(m-1)*tau:tau:i);       
        syM(i-M,:) = syV(i-(m-1)*tau:tau:i);       
    end

    sTEx(isur,1) = cmikra1n(yVh,sxM,yM,k);  % surrogate TE(x->y) values
    sTEy(isur,1) = cmikra1n(xVh,syM,xM,k);  % surrogate TE(y->x) values
end

surM = [sTEx sTEy];
